### ISSUE TITLE
Plugin fails to load for v4.1.0

### ISSUE THREAD

**Issue by ianmetcalf** [Naddiseo/babel-plugin-mjsx#11]
Just tried to update to the latest version and it looks like the built `/lib` directory wasn't included when you published so plugin fails to load.

It may be worth adding the following to `package.json` to avoid this in the future.

``` json
"scripts": {
  "prepublish": "npm run build"
},
```

**Comment by Naddiseo** [comment]
I definitely remember running `npm build` before I published, did npm change it's behaviour recently so that I have to use `npm run build` instead?

Anyway, released a new version with the lib folder, and also added the prepublish command as you suggested, thanks!
