### ISSUE TITLE
Could you add support for .msx file ext?

### ISSUE THREAD

**Issue by kulakowka** [Naddiseo/babel-plugin-mjsx#13]
Could you add support for `*.msx` file extension?

**Comment by Naddiseo** [comment]
I don't think I prevent you from using other file extensions. This plugin just gets passed an AST, so I assume it's up to babel which files are parsed.

**Comment by Naddiseo** [comment]
Closing: this isn't something this plugin has control over.

If using babel directly, you have use the `-x` flag to specify ".msx". If using something like webpack, you can specify which file extensions to use for each loader.
