### ISSUE TITLE
Update for Babel 6

### ISSUE THREAD

**Issue by Naddiseo** [Naddiseo/babel-plugin-mjsx#3]
Refs: http://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by oligot** [comment]
Hi @Naddiseo,

Do you intend to work on this soon, or do you need some help ?

/cc @veggiemonk

**Comment by Naddiseo** [comment]
@oligot, I would happily accept a PR; I have some (work) time constraints at the moment that's causing me to neglect this plugin.

**Comment by veggiemonk** [comment]
@Naddiseo Sorry to hear about your time constraints, I hope it goes well for you. I am sure it is not too difficult to make the change. Plus, there are already a lot of plugins out there like **[this one](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/src/index.js)**.
@oligot Are you on to this? :smile: :v:

**Comment by oligot** [comment]
I'll start to work on it (I first need to understand how babel plugins work).

**Comment by Naddiseo** [comment]
@oligot, I have some time today, so I'm going to give this a stab; I wanted to add some tests too.

**Comment by Naddiseo** [comment]
@oligot, it's going to take some time to finish this. The plugin structure is quite different from babel 5, and I can't find any other (upgraded) plugins for reference; other people seem to be having the same issues that I'm running into when trying to write tests.

**Comment by Naddiseo** [comment]
@oligot, @veggiemonk I've pushed an experimental branch on https://github.com/Naddiseo/babel-plugin-mjsx/tree/babel6 which seems to work. Would you be able to do some limited testing of it and let me know if there any problems?

**Comment by veggiemonk** [comment]
@Naddiseo woaw cool, thanks a lot. Will be testing it today.

**Comment by oligot** [comment]
I will also test it today.

**Comment by sebastiansandqvist** [comment]
@Naddiseo this looks great.

When do you expect to merge this with the main branch?

**Comment by Naddiseo** [comment]
@sebastiansandqvist, my plan was to wait until I can run it across my code base at work, but I also want to wait until babel 6 is more stable before upgrading. This babel 6 version of the plugin has also changed slightly in how it emits white-space, so more feedback from people about any effects of that would be helpful.

**Comment by oligot** [comment]
A bit late, but still useful:
https://github.com/thejameskyle/babel-plugin-handbook
A guide on how to create Babel plugins

**Comment by Naddiseo** [comment]
Created a release. Let me know if you have any problems.

**Comment by veggiemonk** [comment]
By any chance, could you recommend a way to test this with jspm?

**Comment by Naddiseo** [comment]
I have never used jspm before. I would assume that you could add plugins to a `.babelrc` file, and tell jspm to use babel in some way. Sorry I can't be of more help.
