### ISSUE TITLE
Support SVG

### ISSUE THREAD

**Issue by sebastiansandqvist** [Naddiseo/babel-plugin-mjsx#5]
I write a lot of my svg inline and currently the only way to get that to work is to drop out of using mjsx for the svg parts of my code. Are there plans to support SVG in the future?

**Comment by Naddiseo** [comment]
Yes, there is. The current black/white list is an artefact of when this plugin was just a script that only I used, and so reflected my own workflow. The limitation doesn't belong in a public plugin, but as a separate pass, option, or plugin.

However, the check is currently being used to determine if the tag is a component or not, but, I think using "Does the tag begin with a capital letter?" might be a better way to make the distinction.

I would except a PR that removes this limitation ;-)
